### ISSUE TITLE
Clicking on category other than active category deletes all active notifications

### ISSUE THREAD

**Issue by SivaramSS** [SivaramSS/Blurb#2]
When user changes category, cancelNotifcations is being called on active notifications which then calls the respective deleteIntents. So the notifications are deleted from ActiveInfo.

**Comment by ShaneWilton** [comment]
❤️ 💚 💙 💛 💜

**Comment by SivaramSS** [comment]
Called deleteIntent.cancel() before dismissAllNotifications()
